config/routes.rb
Rails.application.routes.draw do
  root to: 'companies#index'
  resources :companies, only: [:index, :show], param: :hash_id
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations', confirmations: 'admins/confirmations', unlocks: 'admins/unlocks' }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :api do
    namespace :v1 do
      resources :articles, only: [:index]
      resources :companies, param: :hash_id, only: [:index, :show] do
        resources :articles, only: [:index], module: :companies
        resources :interns, only: [:index, :show], module: :companies
        resources :job_offers, only: [:index], module: :companies
        resources :benefits, only: [:index], module: :companies
        resources :services, only: [:index], module: :companies
        get :search, on: :collection
      end
      resources :interns, only: [:index]
      post 'auth/:provider/callback', to: 'users#create'
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  include Hashid::Rails
  mount_uploader :avatar, AvatarUploader

  #
  # callbacks
  #
  after_create :set_hash_id

  # Associations
  has_many :company_services, dependent: :destroy
  has_many :company_articles, dependent: :destroy
  has_many :job_offers, dependent: :destroy
  has_many :interns, dependent: :destroy
  has_many :company_benefits, dependent: :destroy
  has_many :company_abouts, dependent: :destroy
  has_many :company_projects, dependent: :destroy

  #
  # validations
  #
  validates :name, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :hash_id, presence: true, uniqueness: { case_sensitive: true }, length: { is: HASH_ID_LENGTH }, on: :update
  validates :average_salary, numericality: { greater_than_or_equal_to: 0 }
  validates :initial_salary, numericality: { greater_than_or_equal_to: 0 }
  validates :average_age, numericality: { greater_than_or_equal_to: 0 }
  validates :employees, numericality: { greater_than_or_equal_to: 0 }
  
  private

  def set_hash_id
    self.hash_id = hashid
    save
  end
end

app/controllers/api/v1/companies/articles_controller.rb
class Api::V1::Companies::ArticlesController < Api::ApplicationController
  before_action :set_company, only: [:index]

  def index
    # TODO: redis対応を必ずする
    articles = @company.company_articles
    render json: articles, each_serializer: CompanyArticleSerializer
  end

  private

  def set_company
    @company = Company.find_by!(hash_id: params[:company_hash_id])
  end
end

app/controllers/api/v1/companies/benefits_controller.rb
class Api::V1::Companies::BenefitsController < Api::ApplicationController
  before_action :set_company, only: [:index]

  def index
    # TODO: redis対応を必ずする
    benefits = @company.company_benefits
    render json: benefits, each_serializer: CompanyBenefitSerializer
  end

  private

  def set_company
    @company = Company.find_by!(hash_id: params[:company_hash_id])
  end
end

app/controllers/api/v1/companies/interns_controller.rb
class Api::V1::Companies::InternsController < Api::ApplicationController
  before_action :set_company, only: [:index, :show]

  def index
    # TODO: redis対応を必ずする
    interns = @company.interns
    render json: interns, each_serializer: InternSerializer
  end

  def show
    intern = @company.interns.find_by(hash_id: params[:id])
    render json: intern, serializer: InternSerializer
  end

  private

  def set_company
    @company = Company.find_by!(hash_id: params[:company_hash_id])
  end
end

app/controllers/api/v1/companies/job_offers_controller.rb
class Api::V1::Companies::JobOffersController < Api::ApplicationController
  before_action :set_company, only: [:index]

  def index
    # TODO: redis対応を必ずする
    job_offers = @company.job_offers
    render json: job_offers, each_serializer: JobOfferSerializer
  end

  private

  def set_company
    @company = Company.find_by!(hash_id: params[:company_hash_id])
  end
end

app/controllers/api/v1/companies/services_controller.rb
class Api::V1::Companies::ServicesController < Api::ApplicationController
  before_action :set_company, only: [:index]

  def index
    # TODO: redis対応を必ずする
    services = @company.company_services
    render json: services, each_serializer: CompanyServiceSerializer
  end

  private

  def set_company
    @company = Company.find_by!(hash_id: params[:company_hash_id])
  end
end

app/controllers/api/v1/companies_controller.rb
class Api::V1::CompaniesController < Api::ApplicationController
  def index
    companies = Company.all
    render json: companies, each_serializer: CompanySerializer
  end

  def show
    options = params[:options] || []
    options_array = build_options_array(options)
    company = Company.includes(options_array).find_by(hash_id: params[:hash_id])
    
    return render json: { error: '企業が見つかりませんでした' }, status: :not_found if company.nil?

    render json: company, serializer: CompanySerializer, scope: options, scope_name: :options
  end

  def search
    query = params[:query]
    return if query.blank?

    compannies = Company.where('name LIKE ?', "%#{query}%")
    render json: compannies, each_serializer: CompanySerializer
  end

  private

  def build_options_array(options)
    options.each_with_object([:company_projects]) do |option, array|
      case option
      when 'company_services' then array << :company_services
      when 'company_benefits' then array << :company_benefits
      when 'company_articles' then array << :company_articles
      when 'company_abouts' then array << :company_abouts
      # when 'job_offers' then array << { job_offers: [job_offer_technologies: [:technology]] }
      when 'job_offers' then array << :job_offers
      when 'interns' then array << :interns
      end
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = if params[:name].present?
                   Company.preload(:company_projects).where("name LIKE ?", "%#{params[:name]}%")
                 else
                   Company.preload(:company_projects).all
                 end

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def show
    @company = Company
               .preload(
                 :company_services,
                 :company_articles,
                 :job_offers,
                 :interns,
                 :company_benefits,
                 :company_abouts,
                 :company_projects
               )
               .find_by(hash_id: params[:hash_id])
  end
end

app/views/companies/index.html.erb
<div class="mx-auto py-6 md:p-6 max-w-7xl">
  <!-- 検索フォーム -->
  <div class="mb-6">
    <%= form_with url: companies_path, method: :get, data: { turbo_frame: "display_area" }, class: "flex items-center relative" do |f| %>
      <%= f.text_field :name, value: params[:name], class: "w-full p-3 pr-10 border border-gray-200 rounded shadow-sm", placeholder: "企業名で検索" %>
      <button type="submit" class="absolute right-3 top-4">
        <span class="material-icons text-gray-400">search</span>
      </button>
    <% end %>
  </div>
  
  <!-- 企業一覧 -->
  <%= turbo_frame_tag "display_area" do %>
    <div>
      <h1 class="text-xl font-bold text-gray-900 mb-3">
        企業一覧
        <span class="text-sm text-gray-600">全<%= @companies.count %>件</span>
      </h1>
    </div>


    <div id="companies-list" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
      <% @companies.each do |company| %>
        <%= link_to company_path(company.hash_id), class: "company-item bg-white border border-gray-200 rounded-lg shadow-md p-6 hover:shadow-lg transition-shadow duration-200 block" do %>
          
          <div class="flex items-center mb-4">
            <span class="material-icons h-10 w-10 mr-3" style="font-size: 32px">domain</span>
            <h2 class="text-xl ml-2 pb-1 font-semibold text-gray-900"><%= company.name %></h2>
          </div>
          
          <div class="w-2/3 md:w-1/2 text-gray-800 mb-4 space-y-2">
            <div class="flex justify-between items-center whitespace-nowrap">
              <p>平均年収:</p>
              <div>
                <span class="text-xl text-gray-900 font-roboto font-bold"><%= number_to_currency(company.average_salary, unit: "", precision: 0) %></span>
                <span class="text-lg">万円</span>
              </div>
            </div>
            <div class="flex justify-between items-center whitespace-nowrap">
              <p>初任給:</p>
              <div>
                <span class="text-xl text-gray-900 font-roboto font-bold"><%= number_to_currency(company.initial_salary, unit: "", precision: 0) %></span>
                <span class="text-lg">万円</span>
              </div>
            </div>
          </div>
          
          
          <div class="border-t border-gray-300 my-4 w-full"></div>

          <p class="text-gray-600 mt-3 mb-4 text-sm"><%= truncate(company.description, length: 40) %></p>

          <div class="flex overflow-x-scroll whitespace-nowrap -m-1" style="-ms-overflow-style: none; scrollbar-width: none;">
            <% company.company_projects.each do |project| %>
              <span class="m-1 border border-black text-black bg-white text-xs  px-2.5 py-0.5 rounded hover:bg-black hover:border-white hover:text-white transition duration-300 ease-in-out"><%= project.name %></span>
            <% end %>
          </div>
          
        <% end %>
      <% end %>
    </div>

  <% end %>
</div>

app/views/companies/show.html.erb
<%= turbo_frame_tag "display_area" do %>

<div class="container mx-auto mt-6 p-6 bg-white rounded-lg shadow-md">
  <div class="flex flex-col md:flex-row items-center justify-between mb-6">
    <!-- 左側: アイコンとタイトル -->
    <div class="flex items-center mb-4 md:mb-0">
      <span class="material-icons h-10 w-10 mr-3" style="font-size: 32px">domain</span>
      <h1 class="text-xl md:text-3xl font-bold text-gray-800"><%= @company.name %></h1>
    </div>
  
    <!-- 右側: 修正依頼ボタン -->
    <div class="mt-2 md:mt-0">
      <button class="px-2 py-1 border border-gray-400 rounded text-sm text-gray-700 hover:bg-gray-100">
        修正依頼
      </button>
    </div>
  </div>
  

  <!-- カテゴリタグ -->
  <div class="flex overflow-x-scroll whitespace-nowrap -m-1" style="-ms-overflow-style: none; scrollbar-width: none;">
    <% @company.company_projects.each do |project| %>
      <span class="m-1 border border-black text-black bg-white text-xs  px-2.5 py-0.5 rounded hover:bg-black hover:border-white hover:text-white transition duration-300 ease-in-out"><%= project.name %></span>
    <% end %>
  </div>

  <!-- 企業概要 -->
  <p class="text-gray-600 my-6 text-base"><%= @company.description %></p>

  <!-- VisionとPurpose -->
  <div data-controller="accordion">
    <% @company.company_abouts.each do |company_about| %>
      <div class="border-b">
        <!-- ボタン部分 -->
        <button data-action="accordion#toggle" data-accordion-target="button" class="flex justify-between items-center w-full py-5 px-3 text-left focus:outline-none">
          <span class="text-sm md:text-lg font-semibold"><%= company_about.title %></span>
          <span data-accordion-target="icon" class="accordion-icon">▶︎</span>
        </button>
        
        <!-- 内容部分 -->
        <div data-accordion-target="content" style="display: none;" class="pb-5 px-3 whitespace-pre-line text-sm">
          <%= company_about.content %>
        </div>
      </div>
    <% end %>
  </div>  

  <!-- 年収と住所、従業員数 -->
  <div class="flex flex-col sm:flex-row justify-between text-gray-800">
    <div class="p-4">
      <div class="mb-4">
        <p class="font-semibold">新卒年収</p>
        <p class="text-2xl font-bold text-gray-900"><%= number_to_currency(@company.initial_salary, unit: "", precision: 0) %> 万円</p>
      </div>
      <div>
        <p class="font-semibold">平均年収</p>
        <p class="text-2xl font-bold text-gray-900"><%= number_to_currency(@company.average_salary, unit: "", precision: 0) %> 万円</p>
        <p class="text-sm text-gray-500">※ 有価証券報告書を参照</p>
      </div>
    </div>
    <div class="mt-2 py-10 px-4">
      <div class="mb-4">
        <p class="">住所</p>
        <p class="text-gray-600"><%= @company.address %></p>
      </div>
      <div>
        <p class="">従業員数</p>
        <p class="text-gray-600"><%= @company.employees %>人</p>
      </div>
    </div>
  </div>

  <div class="border-b"></div>

  <!-- 記事 -->
  <div class="p-3">
    <h1 class="mt-8 text-3xl font-bold text-gray-800">社内エンジニアを知る記事</h1>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 py-4">
      <% @company.company_articles.limit(3).each do |company_article| %>
        <%= link_to company_article.url, target: "_blank", rel: "noopener noreferrer", class: "bg-white rounded-lg shadow-md overflow-hidden transition-transform transform hover:scale-105" do %>
          <!-- ogp画像 -->
          <div class="relative h-48">
            <img src="<%= company_article.ogp_image_url %>" class="object-cover w-full h-full" alt="<%= company_article.title %>">
          </div>
          <!-- 記事情報 -->
          <div class="p-4">
            <h2 class="text-xl font-semibold text-gray-800"><%= company_article.title %></h2>
            <p class="text-gray-600 mt-2 line-clamp-2"><%= company_article.description %></p>
          </div>
        <% end %>
      <% end %>
  </div>
  
    <% if @company.company_articles.count > 3 %>
      <div class="mt-6">
        <%= link_to "もっと見る", "", class: "text-gray-600 hover:text-gray-800 font-semibold" %>
      </div>
    <% end %>
  </div>
  
  

  <div class="border-b"></div>

  <!-- 採用情報 -->

  <div class="p-3">
    <h1 class="mt-8 text-3xl font-bold text-gray-800">採用情報</h1>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 py-4">
      <% @company.job_offers.limit(6).each do |job_offer| %>
        <div class="bg-white rounded-lg shadow-md p-6 hover:shadow-lg transition-shadow duration-200">
          <!-- 職種名 -->
          <h2 class="text-xl font-semibold text-gray-800 mb-2"><%= job_offer.name %></h2>
          <!-- 職種概要 -->
          <p class="text-gray-600 line-clamp-3"><%= job_offer.description %></p>
        </div>
      <% end %>
    </div>

    <% if @company.job_offers.count > 6 %>
      <div class="mt-6">
        <%= link_to "もっと見る", "", class: "text-gray-600 hover:text-gray-800 font-semibold" %>
      </div>
    <% end %>
  </div>
  


  <div class="border-b"></div>
  <!-- サービス -->
  <div class="p-3">
    <h1 class="mt-8 text-3xl font-bold text-gray-800">サービス情報</h1>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 py-4">
      <% @company.company_services.limit(6).each do |service| %>
        <div class="bg-white rounded-lg shadow-md p-6 relative hover:shadow-lg transition-shadow duration-200">
          <!-- サービスURLボタン -->
          <%= link_to service.url, target: "_blank", rel: "noopener noreferrer", class: "absolute top-4 right-4 px-3 py-1 text-gray-500 rounded-lg text-sm flex items-center justify-center" do %>
            <span class="material-icons" style="font-size: 20px">
              open_in_new
            </span>
          <% end %>
  
          <!-- サービス情報 -->
          <h2 class="text-xl font-semibold text-gray-800 mb-2"><%= service.name %></h2>
          <p class="text-gray-600 line-clamp-3 mb-2"><%= service.description %></p>
          <p class="text-sm text-gray-500">
            ローンチ日: <%= format_date(service.launched_at) %>
          </p>
        </div>
      <% end %>
    </div>
  
    <% if @company.company_services.count > 6 %>
      <div class="mt-6">
        <%= link_to "もっと見る", "", class: "text-gray-600 hover:text-gray-800 font-semibold" %>
      </div>
    <% end %>
  </div>


  <div class="border-b"></div>
  <!-- 福利厚生 -->
  <div class="p-3">
    <h1 class="mt-8 text-3xl font-bold text-gray-800">福利厚生</h1>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 py-4">
      <% @company.company_benefits.limit(6).each do |benefit| %>
        <div class="bg-white rounded-lg shadow-md p-6 hover:shadow-lg transition-shadow duration-200">
          <!-- タイトル -->
          <h2 class="text-xl font-semibold text-gray-800 mb-2"><%= benefit.title %></h2>
          <!-- 内容 -->
          <p class="text-gray-600 line-clamp-3"><%= benefit.content %></p>
        </div>
      <% end %>
    </div>

    <% if @company.company_benefits.count > 6 %>
      <div class="mt-6">
        <%= link_to "もっと見る", "", class: "text-gray-600 hover:text-gray-800 font-semibold" %>
      </div>
    <% end %>
  </div>
</div>
<% end %>